### ISSUE TITLE
Pin to openforcefield=0.8.0

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/forcebalance-feedstock#7]
Until https://github.com/leeping/forcebalance/issues/193 is resolved _and a new version of `forcebalance` is released_, this needs to be pinned to 0.8.0.

**Comment by mattwthompson** [comment]
Actually, 

- `openforcefield` is an optional dependency
- `openforcefield` cannot be pinned before its migration to `forcebalance` is complete, and this may not happen until after the holidays

**Comment by jaimergp** [comment]
You can use [`run_constrained`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained) for this!

**Comment by mattwthompson** [comment]
I tested in a new environment - albeit only one OS and Python version - and `mamba install forcebalance openforcefield -c conda-forge -c omnia` gives toolkit 0.8.0 and build number 2 of the most recent version of ForceBalance. Seems to be working for now.
